services:
  postgres:
    container_name: postgres
    image: postgres:16.4-alpine3.20
    env_file:
      - .env.development
    ports:
      - 5432:5432
    networks:
      - api-network

  cliqtree:
    container_name: cliqtree
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - 8080:8080
    networks:
      - api-network
    restart: on-failure
    depends_on:
      - postgres

networks:
  api-network:
    driver: bridge
